server:
  port: 8083

spring:
  application.name: backend-gateway-client
  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://backend-resources:8082/messages
          predicates:
            Path=/messages/**
          filters:
            TokenRelay=

        - id: resources1
          uri: http://backend-resources:8082/test2
          predicates:
            Path=/test2/**
          filters:
            TokenRelay=

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: my_client
            client-secret: Xs2SMfhYAb3y5b8N9mkL90wbNMoRTvw7
            authorization-grant-type: authorization_code
            redirect-uri: "http://backend-gateway-client:8083/login/oauth2/code/{registrationId}"
            scope: openid, message.read
        provider:
          my-provider:
            issuer-uri: http://backend-keycloak-auth:8080/realms/my_realm
